import Head from 'next/head'
import Link from 'next/link'
export const getStaticProps = async()=>{
  const res=await fetch('https://62e9e38d3a5f1572e87056f4.mockapi.io/api/users')
  const data=await res.json()
  return{
    props:{
      users:data
    }
  }
}
function Home ({users}:{users:any})  {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        users.map((user:any)=>{
          return (
            <Link href={'/post/'+user.id} key={user.id}>
              <div className="ml-5 mt-5">Name: <span className="text-red-500 cursor-pointer ml-2">{user.name}</span></div>
            </Link>
          )
        })
      }
      
    </div>
  )
}

export default Home


