import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useState } from "react";
import Header from "./Header";
import Main from "./Main";
const Home: NextPage = () => {
  const [count, setCount] = useState(0);
  const handleIncrease = useCallback(() => {
    setCount(count=>count + 1);
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <div className="flex justify-center mt-10 ">Count:<p className="text-red-600 font-bold">{count}</p></div>
      <Main onIncrease={handleIncrease} />
      
    </div>
  );
};

export default Home;
