import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Header from "./Header";
import Main from "./Main";

interface Todo {
  id: number;
  name?: String;
  image?: String;
}

function Home({ todos }: { todos: Todo[] }) {
  const [count, setCount] = useState(0);
  const handleIncrease = () => {
    setCount((count) => count + 1);
  };
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main onIncrease={handleIncrease} count={count} />
      {todos.map((todo: Todo) => {
        return (
          <div key={todo.id}>
            <p>Name: {todo.name}</p>
          </div>
        );
      })}
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    "https://62e9e38d3a5f1572e87056f4.mockapi.io/api/users"
  );
  const data = await res.json();
  return {
    props: {
      todos: data,
    },
  };
};

export default Home;
